data_path: /tmp
repositories:
- name: test-repo
  remote_url: "https://github.com/LordMathis/GitEcho"
  schedule:  "*/1 * * * *"
  storages:
  - test-storage
storages:
- name: test-storage
  type: s3
  config:
    endpoint:   "http://127.0.0.1:9000"
    access_key:  gitecho
    secret_key:  gitechokey
    bucket_name: gitecho
    disable_ssl: true
    force_path_style: true
    encryption:
      enabled: true
      key: "12345678901234567890123456789012"