version: "3.9"
services:
  minio:
    image: minio/minio:latest
    restart: no
    env_file:
          - .env
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

volumes:
  minio_data:
