version: "3.9"
services:

  gitecho:
    image: gitecho:latest
    build: .
    environment:
      DB_TYPE: postgres
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: gitecho
      DB_PASSWORD: gitecho
      DB_NAME: gitecho
      GITECHO_DATA_PATH: /data
      GITECHO_ENCRYPTION_KEY: # Set your encryption key here
    ports:
      - 8080:8080
    volumes:
      - gitecho_data:/data

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: gitecho
      POSTGRES_PASSWORD: gitecho
      POSTGRES_DB: gitecho
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    environment:
      MINIO_ACCESS_KEY: gitecho
      MINIO_SECRET_KEY: gitecho
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

volumes:
  postgres_data:
  minio_data:
  gitecho_data:
