# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go tests

on:
  push:
    branches:
      - '*'
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - main

jobs:

  minio:
    runs-on: ubuntu-latest
    services:
      minio:
        image: minio/minio
        ports:
          - 9000:9000
        options: --entrypoint "sh -c 'exec /usr/bin/minio server /data'"
        env:
          MINIO_ACCESS_KEY: "gitecho"
          MINIO_SECRET_KEY: "gitechokey"

    steps:
    - name: Wait for Minio to start
      run: sleep 15 # Wait for Minio to start properly


  build:
    runs-on: ubuntu-latest
    needs: minio

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
